# Generated by Django 4.0.2 on 2022-03-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Res',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Res_id', models.IntegerField(primary_key=True, serialize=False)),
                ('res_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iteams',
            fields=[
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('iteam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cat_res')),
            ],
        ),
        migrations.AddField(
            model_name='cat_res',
            name='res_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_cat', to='api.restaurant'),
        ),
    ]
