# Generated by Django 4.0.2 on 2022-03-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat_res',
            old_name='res_id',
            new_name='res',
        ),
        migrations.RenameField(
            model_name='iteams',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
