# Generated by Django 4.0.2 on 2022-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_res_id_cat_res_res_rename_cat_id_iteams_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteams',
            name='iteam_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
